//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SibProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Author { get; set; }
        public Nullable<int> Executor { get; set; }
        public int StatusID { get; set; }
        public int Priority { get; set; }
        public int ProjectID { get; set; }
        public string Comment { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual EMPLOYEE EMPLOYEE1 { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
